SERVICES = [
    {
        "id": "winlink",
        "name": "Winlink RMS Packet",
        "phase": 1,
        "state": "commissioned",
        "rf_role": "transmit-receive",
        "hardware": "AnyTone AT-778UV + DigiRig Mobile",
    },
    {
        "id": "aprs",
        "name": "APRS RX iGate",
        "phase": 1,
        "state": "commissioned",
        "rf_role": "receive-only",
        "hardware": "RTL-SDR",
    },
    {
        "id": "adsb",
        "name": "ADS-B 1090",
        "phase": 1,
        "state": "external-node",
        "rf_role": "receive-only",
        "hardware": "N0JCG Air Traffic node",
    },
    {
        "id": "uat",
        "name": "UAT 978",
        "phase": 1,
        "state": "external-node",
        "rf_role": "receive-only",
        "hardware": "N0JCG Air Traffic node",
    },
    {
        "id": "noaa",
        "name": "NOAA Weather Radio",
        "phase": 1,
        "state": "external-node",
        "rf_role": "receive-only",
        "hardware": "N0JCG Air Traffic node",
    },
    {
        "id": "airband",
        "name": "Civil Airband",
        "phase": 1,
        "state": "external-node",
        "rf_role": "receive-only",
        "hardware": "N0JCG Air Traffic node",
    },
    {
        "id": "scanner",
        "name": "P25 / VHF / UHF Scanner",
        "phase": 2,
        "state": "external-node",
        "rf_role": "receive-only",
        "hardware": "N0JCG Scanner node",
    },
    {
        "id": "planning",
        "name": "Gateway and RF Planning",
        "phase": 3,
        "state": "planned",
        "rf_role": "analysis",
        "hardware": "ROC server",
    },
]
